#!/usr/bin/env python
# This serf query stops the factomd docker container
import subprocess
import os

# Custom utils
from util import serfutil

if serfutil.isFactomd():
	subprocess.call(["docker", "stop", "factomd"])
else:
	print("No factomd")