#!/usr/bin/env python
# This serf query stops the factomd docker container
import subprocess
import os

# Custom utils
from util import serfutil, dockerutil, factomd_control

if serfutil.is_factomd():
	# subprocess.call(["docker", "stop", "factomd"])
	# Using docker api
	try:
		factomd_control.stop_factomd()
	except Exception as e:
		print("Error: " + e)
else:
	print("No factomd")