#!/usr/bin/env python
# This serf query starts the factomd docker container
import subprocess
import os

# Custom utils
from util import serfutil, dockerutil

if serfutil.is_factomd():
	# subprocess.call(["docker", "start", "factomd"])
	# Using docker api
	try:
		client = dockerutil.get_client()
		factomd_container = dockerutil.get_factomd_container(client)
		factomd_container.start()
	except Exception as e:
		print("Error: ",  e)
else:
	print("No factomd")