#!/usr/bin/env python
# This serf query stops the factomd docker container (no output)
import subprocess
import os

# Custom utils
from util import serfutil, dockerutil, factomd_control

if serfutil.is_factomd():
	# subprocess.call(["docker", "start", "factomd"])
	# Using docker api
	try:
		factomd_control.stop_factomd()
	except Exception as e:
else: